print('boolean'.capitalize())
print('CO2 H2O'.find('2'))
print('CO2 H2O'.find('2', 'CO2 H2O'.find('2')+1))
print('Boolean'.startswith('b'))
print('MoNDaY'.lower().capitalize())
print('  Monday'.lstrip())